package javaapplication4;

import java.io.BufferedReader;
import java.io.File;

import java.util.ArrayList;
import java.util.List;
//para poder usar listas observables es necesario importar estas clases sino son exactamentes estas genera error
import org.jdesktop.observablecollections.ObservableList;
import org.jdesktop.observablecollections.ObservableCollections;

/**
 *
 * @author Dylan
 */
public class PlayersDialog extends javax.swing.JDialog {
    
    private List<Players> listaDatos;//lista que se envia como parametro
    private ObservableList<Players> listaObservableDatos;    //lista observable que busca la tabla
    private List<Players> lista = new ArrayList<>();//lista extra para guardar los valores
    VentanaPrincipal vp = new VentanaPrincipal();
    /**
     * Creates new form PlayersDialog
     * @param parent
     * @param modal
     */
    public PlayersDialog(java.awt.Frame parent, boolean modal) {
        listaDatos = new ArrayList<>();
        listaObservableDatos = ObservableCollections.observableList(listaDatos);
        initComponents();
    }

    public void actualizarLista(List<Players> listadoJugadores) {
        this.listaObservableDatos.clear();
        this.listaObservableDatos.addAll(listadoJugadores);
    }
    
    public ObservableList<Players> getListaDatos() {
        return listaObservableDatos;
    }
    
    public void setListaObservableDatos(ObservableList<Players> listaDatos) {
        this.listaObservableDatos = listaDatos;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        group1 = new javax.swing.ButtonGroup();
        group2 = new javax.swing.ButtonGroup();
        group3 = new javax.swing.ButtonGroup();
        group4 = new javax.swing.ButtonGroup();
        group5 = new javax.swing.ButtonGroup();
        group6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        LabelP1 = new javax.swing.JLabel();
        TextFieldP1 = new javax.swing.JTextField();
        LabelP2 = new javax.swing.JLabel();
        TextFieldP2 = new javax.swing.JTextField();
        ButtonPlay = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        RBP1 = new javax.swing.JRadioButton();
        RBT1 = new javax.swing.JRadioButton();
        RBP2 = new javax.swing.JRadioButton();
        RBT2 = new javax.swing.JRadioButton();
        RBP3 = new javax.swing.JRadioButton();
        RBT3 = new javax.swing.JRadioButton();
        RBP4 = new javax.swing.JRadioButton();
        RBT4 = new javax.swing.JRadioButton();
        RBP5 = new javax.swing.JRadioButton();
        RBT5 = new javax.swing.JRadioButton();
        RBP6 = new javax.swing.JRadioButton();
        RBT6 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LabelP1.setText("Player 1");

        LabelP2.setText("Player 2");

        ButtonPlay.setText("PLAY");
        ButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPlayActionPerformed(evt);
            }
        });

        jLabel1.setText("After typing your name choose a vehicle");

        group1.add(RBP1);
        RBP1.setText("War Plane");

        group1.add(RBT1);
        RBT1.setText("War Tank");

        group2.add(RBP2);
        RBP2.setText("War Plane");

        group2.add(RBT2);
        RBT2.setText("War Tank");

        group3.add(RBP3);
        RBP3.setText("War Plane");

        group3.add(RBT3);
        RBT3.setText("War Tank");

        group4.add(RBP4);
        RBP4.setText("War Plane");

        group4.add(RBT4);
        RBT4.setText("War Tank");

        group5.add(RBP5);
        RBP5.setText("War Plane");

        group5.add(RBT5);
        RBT5.setText("War Tank");

        group6.add(RBP6);
        RBP6.setText("War Plane");
        RBP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBP6ActionPerformed(evt);
            }
        });

        group6.add(RBT6);
        RBT6.setText("War Tank");

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${listaDatos}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${first_Player}"));
        columnBinding.setColumnName("First Player");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${second_Player}"));
        columnBinding.setColumnName("Second Player");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(TextFieldP1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(TextFieldP2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelP1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(279, 279, 279)
                        .addComponent(LabelP2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 33, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RBP1)
                                    .addComponent(RBP2)
                                    .addComponent(RBP3))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RBT1)
                                    .addComponent(RBT2)
                                    .addComponent(RBT3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RBP4)
                                .addGap(39, 39, 39)
                                .addComponent(RBT4)
                                .addGap(161, 161, 161))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RBP5)
                                    .addComponent(RBP6))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RBT6)
                                    .addComponent(RBT5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelP1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelP2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldP1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldP2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RBP1)
                            .addComponent(RBT1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBP2)
                            .addComponent(RBT2))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RBT3)
                            .addComponent(RBP3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RBP4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RBT4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RBP5)
                                    .addComponent(RBT5))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RBP6)
                                    .addComponent(RBT6)))
                            .addComponent(ButtonPlay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPlayActionPerformed
//        players = new Players[2];
//        players[0] = new Players(TextFieldP1.getText());
//        players[1] = new Players(TextFieldP2.getText());
        addPlayers();
        addVehicles();
        setVisible(false);
    }//GEN-LAST:event_ButtonPlayActionPerformed

    private void addPlayers(){
        String First = TextFieldP1.getText();//obtiene el texto en el primer jtextfield
        String Second = TextFieldP2.getText();//obtiene el texto en el segundo jtextfield
        Players nuevoJugador = new Players(First, Second);//crea un nuevo jugador
        lista.add(nuevoJugador);//agrega los datos a la lista
        listaDatos = lista;//ingresa los datos a la lista especial para exportar
        actualizarLista(listaDatos);//actualiza la tabla
    }
    
    private void addVehicles(){
        String vehicle1 =null;
        String vehicle2=null;
        String vehicle3=null;
        String vehicle4=null;
        String vehicle5=null;
        String vehicle6=null;
        if(RBP1.isSelected())
         vehicle1 = "You have a War Plane";
        else if(RBT1.isSelected())
         vehicle1 = "You have a War Tank 1";
        
        if(RBP2.isSelected())
         vehicle2 = "You have a War Plane 2";
        else if(RBT2.isSelected())
         vehicle2 = "You have a War Tank 2";
        
        if(RBP3.isSelected())
         vehicle3 = "You have a War Plane 3";
        else if(RBT3.isSelected())
         vehicle3 = "You have a War Tank 3";
        
        if(RBP4.isSelected())
         vehicle4 = "You have a War Plane 4";
        else if(RBT4.isSelected())
         vehicle4 = "You have a War Tank 4";
        
        if(RBP5.isSelected())
         vehicle5 = "You have a War Plane 5";
        else if(RBT5.isSelected())
         vehicle5 = "You have a War Tank 5";
        
        if(RBP6.isSelected())
         vehicle6 = "You have a War Plane 6";
        else if(RBT6.isSelected())
         vehicle6 = "You have a War Tank 6";
        addList(vehicle1,vehicle2,vehicle3,vehicle4,vehicle5,vehicle6);
    }
    
    private void addList(String vehicle1,String vehicle2,String vehicle3,String vehicle4,String vehicle5,String vehicle6){
        System.out.println(vehicle1);
        vp.ComboPlayer1.addItem(vehicle1);
        System.out.println(vehicle2);
        vp.ComboPlayer1.addItem(vehicle2);
        System.out.println(vehicle3);
        vp.ComboPlayer1.addItem(vehicle3);
        System.out.println(vehicle4);
        vp.ComboPlayer1.addItem(vehicle4);
        System.out.println(vehicle5);
        vp.ComboPlayer1.addItem(vehicle5);
        System.out.println(vehicle6);
        vp.ComboPlayer1.addItem(vehicle6);
        
    }
    
    private void RBP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBP6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBP6ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonPlay;
    private javax.swing.JLabel LabelP1;
    private javax.swing.JLabel LabelP2;
    private javax.swing.JRadioButton RBP1;
    private javax.swing.JRadioButton RBP2;
    private javax.swing.JRadioButton RBP3;
    private javax.swing.JRadioButton RBP4;
    private javax.swing.JRadioButton RBP5;
    private javax.swing.JRadioButton RBP6;
    private javax.swing.JRadioButton RBT1;
    private javax.swing.JRadioButton RBT2;
    private javax.swing.JRadioButton RBT3;
    private javax.swing.JRadioButton RBT4;
    private javax.swing.JRadioButton RBT5;
    private javax.swing.JRadioButton RBT6;
    public javax.swing.JTextField TextFieldP1;
    public javax.swing.JTextField TextFieldP2;
    private javax.swing.ButtonGroup group1;
    private javax.swing.ButtonGroup group2;
    private javax.swing.ButtonGroup group3;
    private javax.swing.ButtonGroup group4;
    private javax.swing.ButtonGroup group5;
    private javax.swing.ButtonGroup group6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
