package fynal.project;

import java.io.BufferedReader;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
//para poder usar listas observables es necesario importar estas clases sino son exactamentes estas genera error
import org.jdesktop.observablecollections.ObservableList;
import org.jdesktop.observablecollections.ObservableCollections;

/**
 *
 * @author Usuario
 */
public class PlayersDialog extends javax.swing.JDialog {
    String vehicle1 =null;
    String vehicle2=null;
    String vehicle3=null;
    String vehicle4=null;
    String vehicle5=null;
    String vehicle6=null;
    String First,Second;
    private List<Players> listaDatos;                           //lista que se envia como parametro
    private ObservableList<Players> listaObservableDatos;       //lista observable que busca la tabla
    private List<Players> lista = new ArrayList<>();            //lista extra para guardar los valores
    
    /**
     * Creates new form PlayersDialog
     */
    public PlayersDialog() {
        listaDatos = new ArrayList<>();
        this.setLocationRelativeTo(null);
        listaObservableDatos = ObservableCollections.observableList(listaDatos);
        initComponents();
    }
    
    public void actualizarLista(List<Players> listadoJugadores) {
        this.listaObservableDatos.clear();
        this.listaObservableDatos.addAll(listadoJugadores);
    }
    
    public ObservableList<Players> getListaDatos() {
        return listaObservableDatos;
    }
    
    public void setListaObservableDatos(ObservableList<Players> listaDatos) {
        this.listaObservableDatos = listaDatos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTG1 = new javax.swing.ButtonGroup();
        BTG2 = new javax.swing.ButtonGroup();
        BTG3 = new javax.swing.ButtonGroup();
        BTG4 = new javax.swing.ButtonGroup();
        BTG5 = new javax.swing.ButtonGroup();
        BTG6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        LabelP1 = new javax.swing.JLabel();
        TextFieldP1 = new javax.swing.JTextField();
        LabelP2 = new javax.swing.JLabel();
        TextFieldP2 = new javax.swing.JTextField();
        ButtonPlay = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        RBP1 = new javax.swing.JRadioButton();
        RBT1 = new javax.swing.JRadioButton();
        RBP2 = new javax.swing.JRadioButton();
        RBT2 = new javax.swing.JRadioButton();
        RBP3 = new javax.swing.JRadioButton();
        RBT3 = new javax.swing.JRadioButton();
        RBP4 = new javax.swing.JRadioButton();
        RBT4 = new javax.swing.JRadioButton();
        RBP5 = new javax.swing.JRadioButton();
        RBT5 = new javax.swing.JRadioButton();
        RBP6 = new javax.swing.JRadioButton();
        RBT6 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LabelP1.setText("Player 1");

        LabelP2.setText("Player 2");

        ButtonPlay.setText("PLAY");
        ButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPlayActionPerformed(evt);
            }
        });

        jLabel1.setText("After typing your name choose a vehicle");

        BTG1.add(RBP1);
        RBP1.setText("War Plane");

        BTG1.add(RBT1);
        RBT1.setText("War Tank");

        BTG2.add(RBP2);
        RBP2.setText("War Plane");

        BTG2.add(RBT2);
        RBT2.setText("War Tank");

        BTG3.add(RBP3);
        RBP3.setText("War Plane");

        BTG3.add(RBT3);
        RBT3.setText("War Tank");

        BTG4.add(RBP4);
        RBP4.setText("War Plane");

        BTG4.add(RBT4);
        RBT4.setText("War Tank");

        BTG5.add(RBP5);
        RBP5.setText("War Plane");

        BTG5.add(RBT5);
        RBT5.setText("War Tank");

        BTG6.add(RBP6);
        RBP6.setText("War Plane");
        RBP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBP6ActionPerformed(evt);
            }
        });

        BTG6.add(RBT6);
        RBT6.setText("War Tank");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(TextFieldP1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(TextFieldP2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelP1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(279, 279, 279)
                        .addComponent(LabelP2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 33, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBP1)
                            .addComponent(RBP2)
                            .addComponent(RBP3))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBT1)
                            .addComponent(RBT2)
                            .addComponent(RBT3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RBP4)
                        .addGap(39, 39, 39)
                        .addComponent(RBT4)
                        .addGap(161, 161, 161))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBP5)
                            .addComponent(RBP6))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBT6)
                            .addComponent(RBT5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelP1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelP2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldP1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldP2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RBP1)
                            .addComponent(RBT1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBP2)
                            .addComponent(RBT2))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RBT3)
                            .addComponent(RBP3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RBP4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RBT4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RBP5)
                                    .addComponent(RBT5))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RBP6)
                                    .addComponent(RBT6)))
                            .addComponent(ButtonPlay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPlayActionPerformed
        addPlayers();
        addVehicles();
        setVisible(false);
    }//GEN-LAST:event_ButtonPlayActionPerformed

    private void addPlayers(){
        First = TextFieldP1.getText();                          //obtiene el texto en el primer jtextfield
        Second = TextFieldP2.getText();                         //obtiene el texto en el segundo jtextfield
        Players nuevoJugador = new Players(First, Second);      //crea un nuevo jugador
        lista.add(nuevoJugador);                                //agrega los datos a la lista
        listaDatos = lista;                                     //ingresa los datos a la lista especial para exportar
        actualizarLista(listaDatos);                            //actualiza la tabla
    }
    
    private void addVehicles(){
        if(RBP1.isSelected())
         vehicle1 = "War Plane";
        else if(RBT1.isSelected())
         vehicle1 = "War Tank";
        
        if(RBP2.isSelected())
         vehicle2 = "War Plane";
        else if(RBT2.isSelected())
         vehicle2 = "War Tank";
        
        if(RBP3.isSelected())
         vehicle3 = "War Plane";
        else if(RBT3.isSelected())
         vehicle3 = "War Tank";
        
        if(RBP4.isSelected())
         vehicle4 = "War Plane";
        else if(RBT4.isSelected())
         vehicle4 = "War Tank";
        
        if(RBP5.isSelected())
         vehicle5 = "War Plane";
        else if(RBT5.isSelected())
         vehicle5 = "War Tank";
        
        if(RBP6.isSelected())
         vehicle6 = "War Plane";
        else if(RBT6.isSelected())
         vehicle6 = "War Tank";
    }
    
    private void RBP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBP6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBP6ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BTG1;
    private javax.swing.ButtonGroup BTG2;
    private javax.swing.ButtonGroup BTG3;
    private javax.swing.ButtonGroup BTG4;
    private javax.swing.ButtonGroup BTG5;
    private javax.swing.ButtonGroup BTG6;
    private javax.swing.JButton ButtonPlay;
    private javax.swing.JLabel LabelP1;
    private javax.swing.JLabel LabelP2;
    private javax.swing.JRadioButton RBP1;
    private javax.swing.JRadioButton RBP2;
    private javax.swing.JRadioButton RBP3;
    private javax.swing.JRadioButton RBP4;
    private javax.swing.JRadioButton RBP5;
    private javax.swing.JRadioButton RBP6;
    private javax.swing.JRadioButton RBT1;
    private javax.swing.JRadioButton RBT2;
    private javax.swing.JRadioButton RBT3;
    private javax.swing.JRadioButton RBT4;
    private javax.swing.JRadioButton RBT5;
    private javax.swing.JRadioButton RBT6;
    public javax.swing.JTextField TextFieldP1;
    public javax.swing.JTextField TextFieldP2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
